# Generated by Django 5.0.14 on 2026-06-06 07:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('guardian_name', models.CharField(blank=True, max_length=120)),
                ('guardian_email', models.EmailField(blank=True, max_length=254)),
                ('guardian_phone', models.CharField(blank=True, max_length=40)),
                ('age_years', models.PositiveSmallIntegerField(default=6)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('primary_language', models.CharField(choices=[('zh-Hant', '繁體中文'), ('en', 'English'), ('mixed', '中英文混合')], default='zh-Hant', max_length=16)),
                ('allergies', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('doctor', '醫師'), ('parent', '家長')], default='parent', max_length=16)),
                ('display_name', models.CharField(blank=True, max_length=120)),
                ('organization', models.CharField(blank=True, max_length=160)),
                ('signature_text', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinical_scenario', models.CharField(choices=[('fever', '急性發燒'), ('otitis', '急性中耳炎'), ('vaccine', '疫苗接種門診'), ('asthma', '氣喘急性發作')], max_length=32)),
                ('diagnosis', models.CharField(max_length=160)),
                ('consent_confirmed', models.BooleanField(default=False)),
                ('transcript', models.TextField(blank=True)),
                ('doctor_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('recording', '錄製中'), ('processing', '產生中'), ('review', '待審核'), ('approved', '已發布')], default='draft', max_length=20)),
                ('share_token', models.CharField(editable=False, max_length=80, unique=True)),
                ('audio_delete_after', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('signed_by', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='core.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TranscriptChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('source', models.CharField(choices=[('browser', 'Browser audio'), ('manual', 'Manual transcript'), ('stt', 'Speech-to-text')], default='browser', max_length=20)),
                ('text', models.TextField(blank=True)),
                ('audio_file', models.FileField(blank=True, upload_to='audio/%Y/%m/%d/')),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='core.visit')),
            ],
            options={
                'ordering': ['sequence', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisitOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_summary', models.TextField()),
                ('child_explanation', models.TextField()),
                ('school_note', models.TextField()),
                ('warning_signs', models.JSONField(blank=True, default=list)),
                ('follow_up_plan', models.TextField(blank=True)),
                ('ai_provider', models.CharField(default='mock', max_length=40)),
                ('ai_model', models.CharField(blank=True, max_length=120)),
                ('prompt_version', models.CharField(default='pedihealth-v3', max_length=40)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='output', to='core.visit')),
            ],
        ),
    ]
