# Generated by Django 5.0.14 on 2026-06-06 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('female', '女'), ('male', '男'), ('other', '其他'), ('unknown', '未填')], default='unknown', max_length=16),
        ),
        migrations.AddField(
            model_name='visitoutput',
            name='parent_education',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visitoutput',
            name='patient_education',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visitoutput',
            name='visit_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='clinical_scenario',
            field=models.CharField(choices=[('general', '一般兒科看診'), ('fever', '急性發燒'), ('otitis', '急性中耳炎'), ('vaccine', '疫苗接種門診'), ('asthma', '氣喘急性發作')], max_length=32),
        ),
    ]
